Repository BnjmnZmmrmn/GamesmanClassic, pull requests merged in 2024-10, with the labels that each got.

#1 created m*.c template for jan 4x4
  src/mjan.c
Labels: enhancement

#3 impl isPrimitive
  src/mjan.c
Labels: enhancement

#5 bugfixes Primitive
  src/mjan.c
Labels: bug

#4 Dev aj
  src/mjan.c
Labels: enhancement

#8 add in MakeFile
  src/Makefile.in
Labels: enhancement, help wanted

#7 implemented ValidtextInput, ConvertTextInputToMove, MoveToString
  src/mjan.c
Labels: bug, enhancement

#6 PrintPosition impl
  src/mjan.c
Labels: enhancement

#9 fixed errors and added variant enum
  src/mjan.c
Labels: bug, enhancement

#13 PositionToStr impl
  src/mjan.c
Labels: kind/feature

#14 PositionToAutoGUIString impl
  src/mjan.c
Labels: kind/feature

#15 MoveToAutoGUIString impl
  src/mjan.c
Labels: kind/feature

#19 Primitive fix
  src/mjan.c
Labels: kind/bug

#18 Fixed Legend and Moves
  bin/Makefile
  bin/README
  bin/XGamesman
  bin/XGamesman.new
  bin/XGamesman.old
  bin/Xm1210
  bin/Xm369mm
  bin/Xm3spot
  bin/XmLgame
  bin/Xmabalone
  bin/Xmachi
  bin/Xmasalto
  bin/Xmbaghchal
  bin/Xmchange
  bin/Xmcmass
  bin/Xmcon
  bin/Xmctoi
  bin/Xmctoi.silver
  bin/Xmdao
  bin/Xmdinododgem
  bin/Xmdnb
  bin/Xmdodgem
  bin/Xmfoxes
  bin/Xmhshogi
  bin/Xmiceblocks
  bin/Xmkono
  bin/Xmlewth
  bin/Xmlgame3
  bin/Xmlite3
  bin/Xmmancala
  bin/Xmnim
  bin/Xmooe
  bin/Xmothello
  bin/Xmqland
  bin/Xmquarto
  bin/Xmqx
  bin/Xmrubix
  bin/Xmseega
  bin/Xmsim
  bin/XmslideN
  bin/Xmsnake
  bin/Xmstt
  bin/Xmstt.bronze
  bin/Xmtactix
  bin/Xmtactix.silver
  bin/Xmtootnotto
  bin/Xmtore
  bin/Xmttt
  bin/Xmttt3
  bin/Xmttt3tier
  bin/Xmwin4
  bin/Xmwuzhi
  bin/allgamesinfo
  bin/dbcmp.py
  bin/games.txt
  bin/newsolve
  bin/tierdbcmp.py
  src/mjan.c
Labels: kind/feature
